services:
  backend-1:
    image: node:lts
    container_name: backend-1
    restart: unless-stopped
    ports:
      - "5000:5000"
    working_dir: /server
    volumes:
      - ./:/server
    command: >
      bash -c "npm install && npm start"
    env_file:
      - .env
    networks:
      edlus:
        ipv4_address: 10.10.0.4
networks: 
  edlus:
    external: true